spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: tobi
    password: tobithebest
    url: jdbc:postgresql://localhost:5432/contacts_book
  mvc:
    hidden-method:
      filter:
        enabled: true