spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 0191
    url: jdbc:postgresql://localhost:5432/contacts_book
  mvc:
    hidden-method:
      filter:
        enabled: true